spring:
  autoconfigure:
    exclude:
       - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
       - org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration
  application:
    name: microservicio-peces
  config:
    import: optional:configserver:${CONFIG_URL:http://microservicio-configuraciones.railway.internal:8888}

 